# Generated by Django 5.0.2 on 2024-03-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio", models.FileField(upload_to="audio/")),
            ],
        ),
        migrations.DeleteModel(
            name="CalmSongs",
        ),
        migrations.DeleteModel(
            name="HappySongs",
        ),
        migrations.DeleteModel(
            name="MotivationalSongs",
        ),
        migrations.DeleteModel(
            name="SadSongs",
        ),
    ]
